export const config = {
  mode: "paper",
  symbol: "BTC-USDT",
  symbols: ["BTC-USDT", "ETH-USDT", "SOL-USDT"],
  initialBalance: 1000,
  riskPerTrade: 0.01,
  takeProfitPct: 0.006,
  stopLossPct: 0.004,
  bar: "5m",
  candlesLimit: 100,
  emaFast: 20,
  emaSlow: 50,
  rsiPeriod: 14,
  atrPeriod: 14,
  volumePeriod: 20,
  feeRate: 0.0008,
  maxPositionValuePct: 0.3,
  atrStopMultiplier: 1.2,
  atrTakeMultiplier: 1.8,
  minRsiForLong: 45,
  maxRsiForLong: 65,
  minVolumeFactor: 1.05,
  useHtfFilter: true,
  htfBar: "1H",
  htfCandlesLimit: 500,
  htfEmaFast: 20,
  htfEmaSlow: 50,
  paperOnly: true,
  backtestCandlesLimit: 2000,
  activeProfile: "balanced",
  activeStrategy: "trendMomentum",
  strategies: {
    trendMomentum: {
      enabled: true,
      label: "Trend Momentum",
    },
    trendPullback: {
      enabled: true,
      label: "Trend Pullback",
    },
  },
  pullbackLookback: 8,
  pullbackTolerancePct: 0.002,
  strategyProfiles: {
    conservative: {
      emaFast: 20,
      emaSlow: 50,
      minRsiForLong: 50,
      maxRsiForLong: 62,
      minVolumeFactor: 1.2,
      atrStopMultiplier: 1.0,
      atrTakeMultiplier: 1.8,
      minScoreForEntry: 85,
      useHtfFilter: true,
    },
    balanced: {
      emaFast: 20,
      emaSlow: 50,
      minRsiForLong: 45,
      maxRsiForLong: 65,
      minVolumeFactor: 1.05,
      atrStopMultiplier: 1.2,
      atrTakeMultiplier: 1.8,
      minScoreForEntry: 80,
      useHtfFilter: true,
    },
    aggressive: {
      emaFast: 9,
      emaSlow: 21,
      minRsiForLong: 42,
      maxRsiForLong: 68,
      minVolumeFactor: 0.9,
      atrStopMultiplier: 1.0,
      atrTakeMultiplier: 1.5,
      minScoreForEntry: 70,
      useHtfFilter: true,
    },
  },
  telegramEnabled: true,
  notifyOnHold: false,
  notifyOnBuy: true,
  notifyOnClose: true,
  notifyOnLoopStart: true,
};
