export const config = {
  mode: "paper",
  symbol: "BTC-USDT",
  initialBalance: 1000,
  riskPerTrade: 0.01,
  takeProfitPct: 0.006,
  stopLossPct: 0.004,
  bar: "5m",
  candlesLimit: 100,
  emaFast: 20,
  emaSlow: 50,
  rsiPeriod: 14,
  atrPeriod: 14,
  volumePeriod: 20,
  feeRate: 0.0008,
  maxPositionValuePct: 0.3,
  atrStopMultiplier: 1.2,
  atrTakeMultiplier: 1.8,
  minRsiForLong: 45,
  maxRsiForLong: 65,
  minVolumeFactor: 1.05,
  telegramEnabled: true,
  notifyOnHold: false,
  notifyOnBuy: true,
  notifyOnClose: true,
  notifyOnLoopStart: true,
};
